// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/api.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb/api.proto

It has these top-level messages:
	FlipRequest
	FlipStringRequest
	FlipIntegerRequest
	FlipResponse
	HealthRequest
	HealthResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FlipRequest struct {
	FeatureTag string `protobuf:"bytes,1,opt,name=feature_tag,json=featureTag" json:"feature_tag,omitempty"`
}

func (m *FlipRequest) Reset()                    { *m = FlipRequest{} }
func (m *FlipRequest) String() string            { return proto.CompactTextString(m) }
func (*FlipRequest) ProtoMessage()               {}
func (*FlipRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FlipRequest) GetFeatureTag() string {
	if m != nil {
		return m.FeatureTag
	}
	return ""
}

type FlipStringRequest struct {
	FeatureTag   string `protobuf:"bytes,1,opt,name=feature_tag,json=featureTag" json:"feature_tag,omitempty"`
	FeatureValue string `protobuf:"bytes,2,opt,name=feature_value,json=featureValue" json:"feature_value,omitempty"`
}

func (m *FlipStringRequest) Reset()                    { *m = FlipStringRequest{} }
func (m *FlipStringRequest) String() string            { return proto.CompactTextString(m) }
func (*FlipStringRequest) ProtoMessage()               {}
func (*FlipStringRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FlipStringRequest) GetFeatureTag() string {
	if m != nil {
		return m.FeatureTag
	}
	return ""
}

func (m *FlipStringRequest) GetFeatureValue() string {
	if m != nil {
		return m.FeatureValue
	}
	return ""
}

type FlipIntegerRequest struct {
	FeatureTag   string `protobuf:"bytes,1,opt,name=feature_tag,json=featureTag" json:"feature_tag,omitempty"`
	FeatureValue int64  `protobuf:"varint,2,opt,name=feature_value,json=featureValue" json:"feature_value,omitempty"`
}

func (m *FlipIntegerRequest) Reset()                    { *m = FlipIntegerRequest{} }
func (m *FlipIntegerRequest) String() string            { return proto.CompactTextString(m) }
func (*FlipIntegerRequest) ProtoMessage()               {}
func (*FlipIntegerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FlipIntegerRequest) GetFeatureTag() string {
	if m != nil {
		return m.FeatureTag
	}
	return ""
}

func (m *FlipIntegerRequest) GetFeatureValue() int64 {
	if m != nil {
		return m.FeatureValue
	}
	return 0
}

type FlipResponse struct {
	Activated bool `protobuf:"varint,1,opt,name=activated" json:"activated,omitempty"`
}

func (m *FlipResponse) Reset()                    { *m = FlipResponse{} }
func (m *FlipResponse) String() string            { return proto.CompactTextString(m) }
func (*FlipResponse) ProtoMessage()               {}
func (*FlipResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FlipResponse) GetActivated() bool {
	if m != nil {
		return m.Activated
	}
	return false
}

type HealthRequest struct {
}

func (m *HealthRequest) Reset()                    { *m = HealthRequest{} }
func (m *HealthRequest) String() string            { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()               {}
func (*HealthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type HealthResponse struct {
	Health    string `protobuf:"bytes,1,opt,name=health" json:"health,omitempty"`
	FlipCache string `protobuf:"bytes,2,opt,name=flip_cache,json=flipCache" json:"flip_cache,omitempty"`
	FlipStore string `protobuf:"bytes,3,opt,name=flip_store,json=flipStore" json:"flip_store,omitempty"`
}

func (m *HealthResponse) Reset()                    { *m = HealthResponse{} }
func (m *HealthResponse) String() string            { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()               {}
func (*HealthResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *HealthResponse) GetHealth() string {
	if m != nil {
		return m.Health
	}
	return ""
}

func (m *HealthResponse) GetFlipCache() string {
	if m != nil {
		return m.FlipCache
	}
	return ""
}

func (m *HealthResponse) GetFlipStore() string {
	if m != nil {
		return m.FlipStore
	}
	return ""
}

func init() {
	proto.RegisterType((*FlipRequest)(nil), "pb.FlipRequest")
	proto.RegisterType((*FlipStringRequest)(nil), "pb.FlipStringRequest")
	proto.RegisterType((*FlipIntegerRequest)(nil), "pb.FlipIntegerRequest")
	proto.RegisterType((*FlipResponse)(nil), "pb.FlipResponse")
	proto.RegisterType((*HealthRequest)(nil), "pb.HealthRequest")
	proto.RegisterType((*HealthResponse)(nil), "pb.HealthResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Flip service

type FlipClient interface {
	IsFlip(ctx context.Context, in *FlipRequest, opts ...grpc.CallOption) (*FlipResponse, error)
	IsFlipString(ctx context.Context, in *FlipStringRequest, opts ...grpc.CallOption) (*FlipResponse, error)
	IsFlipInteger(ctx context.Context, in *FlipIntegerRequest, opts ...grpc.CallOption) (*FlipResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type flipClient struct {
	cc *grpc.ClientConn
}

func NewFlipClient(cc *grpc.ClientConn) FlipClient {
	return &flipClient{cc}
}

func (c *flipClient) IsFlip(ctx context.Context, in *FlipRequest, opts ...grpc.CallOption) (*FlipResponse, error) {
	out := new(FlipResponse)
	err := grpc.Invoke(ctx, "/pb.Flip/IsFlip", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flipClient) IsFlipString(ctx context.Context, in *FlipStringRequest, opts ...grpc.CallOption) (*FlipResponse, error) {
	out := new(FlipResponse)
	err := grpc.Invoke(ctx, "/pb.Flip/IsFlipString", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flipClient) IsFlipInteger(ctx context.Context, in *FlipIntegerRequest, opts ...grpc.CallOption) (*FlipResponse, error) {
	out := new(FlipResponse)
	err := grpc.Invoke(ctx, "/pb.Flip/IsFlipInteger", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flipClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := grpc.Invoke(ctx, "/pb.Flip/Health", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Flip service

type FlipServer interface {
	IsFlip(context.Context, *FlipRequest) (*FlipResponse, error)
	IsFlipString(context.Context, *FlipStringRequest) (*FlipResponse, error)
	IsFlipInteger(context.Context, *FlipIntegerRequest) (*FlipResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
}

func RegisterFlipServer(s *grpc.Server, srv FlipServer) {
	s.RegisterService(&_Flip_serviceDesc, srv)
}

func _Flip_IsFlip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlipServer).IsFlip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Flip/IsFlip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlipServer).IsFlip(ctx, req.(*FlipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flip_IsFlipString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlipStringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlipServer).IsFlipString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Flip/IsFlipString",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlipServer).IsFlipString(ctx, req.(*FlipStringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flip_IsFlipInteger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlipIntegerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlipServer).IsFlipInteger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Flip/IsFlipInteger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlipServer).IsFlipInteger(ctx, req.(*FlipIntegerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Flip_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlipServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Flip/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlipServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Flip_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Flip",
	HandlerType: (*FlipServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsFlip",
			Handler:    _Flip_IsFlip_Handler,
		},
		{
			MethodName: "IsFlipString",
			Handler:    _Flip_IsFlipString_Handler,
		},
		{
			MethodName: "IsFlipInteger",
			Handler:    _Flip_IsFlipInteger_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Flip_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/api.proto",
}

func init() { proto.RegisterFile("pb/api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x4f, 0x8b, 0xda, 0x40,
	0x18, 0xc6, 0x51, 0x4b, 0xa8, 0xaf, 0xb1, 0xd6, 0x17, 0x2a, 0x21, 0x58, 0x2a, 0xe9, 0xa5, 0x87,
	0x92, 0x54, 0x7b, 0x68, 0xef, 0x42, 0xa9, 0x87, 0x5e, 0xb4, 0x14, 0xda, 0x8b, 0x4c, 0xec, 0x18,
	0x07, 0x42, 0x66, 0x9a, 0x19, 0xbd, 0x14, 0x0f, 0xed, 0x57, 0xd8, 0x8f, 0xb6, 0x5f, 0x61, 0x3f,
	0xc8, 0x32, 0x7f, 0xb2, 0x49, 0x16, 0x61, 0x17, 0xf6, 0x66, 0x7e, 0x79, 0xe7, 0xf7, 0xbc, 0xe3,
	0x43, 0xc0, 0x17, 0x69, 0x42, 0x04, 0x8b, 0x45, 0xc9, 0x15, 0xc7, 0xae, 0x48, 0xc3, 0x69, 0xc6,
	0x79, 0x96, 0x53, 0x4d, 0x13, 0x52, 0x14, 0x5c, 0x11, 0xc5, 0x78, 0x21, 0xed, 0x44, 0x14, 0xc3,
	0xe0, 0x4b, 0xce, 0xc4, 0x9a, 0xfe, 0x39, 0x52, 0xa9, 0xf0, 0x0d, 0x0c, 0xf6, 0x94, 0xa8, 0x63,
	0x49, 0xb7, 0x8a, 0x64, 0x41, 0x67, 0xd6, 0x79, 0xd7, 0x5f, 0x83, 0x43, 0xdf, 0x49, 0x16, 0xfd,
	0x84, 0xb1, 0x9e, 0xdf, 0xa8, 0x92, 0x15, 0xd9, 0x63, 0x4f, 0xe1, 0x5b, 0x18, 0x56, 0x03, 0x27,
	0x92, 0x1f, 0x69, 0xd0, 0x35, 0x23, 0xbe, 0x83, 0x3f, 0x34, 0x8b, 0x7e, 0x01, 0x6a, 0xf5, 0xaa,
	0x50, 0x34, 0xa3, 0xe5, 0xd3, 0xdc, 0xbd, 0x7b, 0xee, 0xf7, 0xe0, 0xdb, 0x6b, 0x4a, 0xc1, 0x0b,
	0x49, 0x71, 0x0a, 0x7d, 0xb2, 0x53, 0xec, 0x44, 0x14, 0xfd, 0x6d, 0x9c, 0xcf, 0xd7, 0x35, 0x88,
	0x46, 0x30, 0xfc, 0x4a, 0x49, 0xae, 0x0e, 0x6e, 0x89, 0x68, 0x0f, 0x2f, 0x2a, 0xe0, 0x04, 0x13,
	0xf0, 0x0e, 0x86, 0xb8, 0x8d, 0xdc, 0x13, 0xbe, 0x06, 0xd8, 0xe7, 0x4c, 0x6c, 0x77, 0x64, 0x77,
	0xa8, 0xae, 0xd9, 0xd7, 0x64, 0xa9, 0xc1, 0xdd, 0x6b, 0xa9, 0x78, 0x49, 0x83, 0x5e, 0xfd, 0x7a,
	0xa3, 0xc1, 0xe2, 0x5f, 0x0f, 0x9e, 0xe9, 0x3d, 0xf1, 0x1b, 0x78, 0x2b, 0x69, 0x7e, 0x8d, 0x62,
	0x91, 0xc6, 0x8d, 0x8a, 0xc2, 0x97, 0x35, 0xb0, 0xbb, 0x44, 0xb3, 0xff, 0xd7, 0x37, 0x57, 0xdd,
	0x10, 0x83, 0xe4, 0x34, 0x4f, 0x98, 0xd4, 0xba, 0xe4, 0x6f, 0xe3, 0x4f, 0x3b, 0xa3, 0x00, 0xdf,
	0xea, 0x6c, 0x6f, 0xf8, 0xaa, 0x72, 0xb4, 0x7a, 0xbc, 0xa0, 0xfe, 0x64, 0xd4, 0x73, 0x4c, 0x1a,
	0x6a, 0x69, 0xce, 0xb4, 0x13, 0xea, 0x27, 0xd3, 0xc1, 0x19, 0x25, 0x0c, 0x6d, 0xa2, 0xab, 0x13,
	0x27, 0x95, 0xbb, 0xdd, 0xef, 0x85, 0xcc, 0xcf, 0x26, 0x73, 0x81, 0x1f, 0x1a, 0x99, 0xcc, 0x1e,
	0x7a, 0x20, 0x74, 0x09, 0x9e, 0xad, 0x09, 0xc7, 0xda, 0xda, 0xea, 0x30, 0xc4, 0x26, 0x72, 0x51,
	0x68, 0xa2, 0x7c, 0x04, 0x1d, 0x65, 0x1b, 0x4c, 0x3d, 0xf3, 0x61, 0x7c, 0xbc, 0x0d, 0x00, 0x00,
	0xff, 0xff, 0xca, 0x4b, 0xb0, 0xdb, 0x4a, 0x03, 0x00, 0x00,
}
